# Trabalho Prático Módulo 1

In [1]:
import pandas as pd
import numpy as np
import plotly.express as px
from sklearn.linear_model import LinearRegression

In [2]:
base_custo_diaria = pd.read_csv('regressao_linear_2.csv', sep = ';')

In [3]:
base_custo_diaria.head()

qtd_pessoas  valor_diaria
0            1           150
1            3           200
2            4           650
3            6           499
4            7           549

In [4]:
base_custo_diaria.describe()

qtd_pessoas  valor_diaria
count    30.000000     30.000000
mean     28.600000   1648.633333
std      18.189804    950.522197
min       1.000000    150.000000
25%      13.500000    869.250000
50%      26.000000   1627.500000
75%      44.500000   2497.000000
max      60.000000   3300.000000

In [5]:
base_custo_diaria.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 2 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   qtd_pessoas   30 non-null     int64
 1   valor_diaria  30 non-null     int64
dtypes: int64(2)
memory usage: 608.0 bytes


In [6]:
base_custo_diaria.isna().sum()

qtd_pessoas     0
valor_diaria    0
dtype: int64

In [7]:
#base_custo_diaria.groupby(['qtd_pessoas']).describe()

In [8]:
x_base = base_custo_diaria.iloc[:, 0].values
y_base = base_custo_diaria.iloc[:, 1].values

In [9]:
np.corrcoef(x_base, y_base)

array([[1.        , 0.97866601],
       [0.97866601, 1.        ]])

In [10]:
x_shape = x_base.reshape(-1, 1)
x_shape[:5]

array([[1],
       [3],
       [4],
       [6],
       [7]])

In [11]:
lr = LinearRegression()
lr.fit(x_shape, y_base)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [12]:
# constante alpha (a)
lr.intercept_

186.00229281307384

In [13]:
# constante beta (b)
lr.coef_

array([51.14094547])

In [14]:
previsoes = lr.predict(x_shape)
previsoes[:5]

array([237.14323829, 339.42512923, 390.5660747 , 492.84796565,
       543.98891112])

In [15]:
gf = px.scatter(x = x_base, y = y_base)
gf.add_scatter(x = x_base, y = previsoes, name = 'previsões')
gf.show()

In [16]:
# previsão pelo método:
lr.predict([[57]])

array([3101.03618476])

In [17]:
# diferença entre base e predito
i = 25
y_base[np.where(x_base == i)[0][0]] - lr.predict([[i]])[0]

35.47407036851746

In [18]:
# score
lr.score(x_shape, y_base)

0.957787164932263

In [19]:
# erro absoluto
from sklearn.metrics import mean_squared_error, mean_absolute_error
mean_absolute_error(y_base, previsoes)


138.91296481574125