# Trabalho Prático Módulo 1

In [1]:
import pandas as pd
import numpy as np
import plotly.express as px
from sklearn.linear_model import LinearRegression

In [2]:
base_custo_diaria = pd.read_csv('trabalho_pratico.csv', sep = ';')

In [3]:
base_custo_diaria.head()

qtd_pessoas  valor_diaria
0            1           150
1            3           200
2            4           650
3            6           499
4            7           549

In [4]:
base_custo_diaria.describe()

qtd_pessoas  valor_diaria
count    30.000000     30.000000
mean     28.600000   1648.633333
std      18.189804    950.522197
min       1.000000    150.000000
25%      13.500000    869.250000
50%      26.000000   1627.500000
75%      44.500000   2497.000000
max      60.000000   3300.000000

In [5]:
base_custo_diaria.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 2 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   qtd_pessoas   30 non-null     int64
 1   valor_diaria  30 non-null     int64
dtypes: int64(2)
memory usage: 608.0 bytes


In [6]:
base_custo_diaria.isna().sum()

qtd_pessoas     0
valor_diaria    0
dtype: int64

In [20]:
# 8. Qual o valor de correlação entre as variáveis qtd_pessoas e valor da diária?
x_base = base_custo_diaria.iloc[:, 0].values
y_base = base_custo_diaria.iloc[:, 1].values
np.corrcoef(x_base, y_base)

array([[1.        , 0.97866601],
       [0.97866601, 1.        ]])

In [21]:
# 9. Qual o valor retornado intercept da previsão?
x_shape = x_base.reshape(-1, 1)

lr = LinearRegression()
lr.fit(x_shape, y_base)

lr.intercept_

186.00229281307384

In [23]:
# 10. Qual o valor da previsão realizada pelo modelo de regressão para a qtd_pessoas = 20 ?
qtd_pressoas = 20
lr.intercept_ + lr.coef_ * qtd_pressoas

array([1208.82120227])

In [24]:
# 11. Qual o valor da previsão realizada pelo modelo de regressão para a qtd_pessoas = 57 ?
lr.predict([[57]])

array([3101.03618476])

In [25]:
# 12. Qual a difença entre o valor predito e o valor real do valor da diária para a quantidade de pessoas = 25
qtd_pressoas = 25
y_base[np.where(x_base == qtd_pressoas)[0][0]] - lr.predict([[qtd_pressoas]])[0]

35.47407036851746

In [26]:
# 13. Qual foi o score obtido pelo algoritmo de regressão?
lr.score(x_shape, y_base)

0.9577871649322629

In [27]:
# 14. Qual o valor obtido para mean_absolute_error?
from sklearn.metrics import mean_squared_error, mean_absolute_error
previsoes = lr.predict(x_shape)
mean_absolute_error(y_base, previsoes)

138.91296481574125

In [15]:
gf = px.scatter(x = x_base, y = y_base)
gf.add_scatter(x = x_base, y = previsoes, name = 'previsões')
gf.show()